%Configuration file of Machine Learning Algorithm Tester (MLAT)
% 
%  Before run main.m, please edit this file first.
%
% See also main.m

% Author: Yanan Sun
% Author: LCY-Hugepanda
% Copyright: lcy.hugepanda@gmail.org

global MLAT_Conf;

%% ----------Configuration Part (Please edit before run MLAT_Main.m) --------------
% Configurations about the displaying
format compact

% Configurations about the evaluating precedures
test_type = 1;  % 实验测试类型：1--多次重复CV的多数据集标准测试   2--二维数据可视化实验

if 1 == test_type
    num_cv = 5; % Numbers of Cross Validation (CV)
    num_repeat = 1; % Numbers of repeats of CV
elseif 2 == test_type
    % 占位
end

% Algorithms to be evaluated
% 算法可能用到包括dd_tools,lcy-prototypealgo和
    % 实际测试，集成算法
% algo_list ={...
%     'Meta_Bagging(#''OCLT_AlgoLibsvmOCSVM(A, ''''default'''', 0.1, A)''#,#20#,#''votec''#)',...
%     'Meta_Bagging(#''parzen_dd(A,0.1)''#,#20#,#''votec''#)',...
%     'Meta_Bagging(#''gauss_dd(A,0.1)''#,#20#,#''votec''#)',...
%     'Meta_Bagging(#''mst_dd(A,0.1)''#,#20#,#''votec''#)',...
%     'Meta_Bagging(#''nndd(A,0.1)''#,#20#,#''votec''#)'...
%     };
    %单算法测试
algo_list ={...
    %'NoOutlier_Rankboost(#0.1#,#20#,#''gendatblockout''#)',...
    %'DDTools_Rankboost(#0.1#,#20#)',...
%     'OCCBoost(#0.05#,#600#,#0.01#)',...
%     'OCCBoost(#0.05#,#600#,#0.02#)',...
%     'OCCBoost(#0.05#,#600#,#0.03#)',...
%     'OCCBoost(#0.05#,#600#,#0.04#)',...
%     'OCCBoost(#0.05#,#600#,#0.05#)',...
%     'OCCBoost(#0.05#,#600#,#0.06#)',...
%     'OCCBoost(#0.05#,#600#,#0.07#)',...
%     'OCCBoost(#0.05#,#600#,#0.08#)',...
%     'OCCBoost(#0.05#,#600#,#0.09#)',...
%     'OCCBoost(#0.05#,#600#,#0.1#)',...
%     'OCCBoost(#0.05#,#600#,#0.2#)',...
%     'OCCBoost(#0.05#,#600#,#0.3#)',...
%     'OCCBoost(#0.05#,#600#,#0.4#)',...
%     'OCCBoost(#0.05#,#600#,#0.5#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.01#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.02#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.03#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.04#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.05#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.06#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.07#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.08#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.09#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.1#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.2#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.3#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.4#)',...
    'NoOutlier_Rankboost(#0.05#,#100#,#''gendatblockout''#,#0.5#)'
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.01#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.02#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.03#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.04#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.05#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.06#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.07#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.08#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.09#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.1#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.2#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.3#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.4#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatout''#,#0.5#)'
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.01#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.02#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.03#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.04#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.05#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.06#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.07#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.08#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.09#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.1#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.2#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.3#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.4#)',...
%     'NoOutlier_Rankboost(#0.05#,#100#,#''gendatoutg''#,#0.5#)'
	%'DDTools_GaussDD(#0.05#)',...
    %'DDTools_ParzenDD(#0.05#)',...
    %'DDTools_NNDD(#0.05#)',...
    %'Libsvm_OCSVM(#0.05#)' ,...
   % 'DDTools_incSVDD(#0.05#)',...
    %'DDTools_LOF(#0.05#)',...
    %'DDTools_LOCI(#0.05#)',...
    %'DDTools_GaussDD(#0.05#)',...
    %'DDTools_ParzenDD(#0.05#)',...
    %'DDTools_LOF(#0.05#)',...
    %'DDTools_LOCI(#0.05#)',...
   % 'Libsvm_OCSVM(#0.05#)' ,...
    %    'DDTools_incSVDD(#0.05#)'
    %'DDTools_NNDD(#0.05#)',...
    %'DDTools_GaussDD(#0.1#)',...
     'Ensemble_Classification(#3#,#''fcm''#,#''mymst_dd''#,#votec#)',...
     'Ensemble_Classification(#3#,#''fcm''#,#''mst_dd''#,#votec#)',...
     'Ensemble_Classification(#3#,#''fcm''#,#''gauss_dd''#,#votec#)',...
     'DDTools_Incsvdd(#0.1#)'
%      'Ensemble_Classification(#3#,#''emclust''#,#''mst_dd''#,#maxc#)',...
%      'Ensemble_Classification(#3#,#''hclust''#,#''gauss_dd''#,#maxc#)'
    % 'Ensemble_Classification(#3#,#''kcentres''#,#''gauss_dd''#,#maxc#)',...
    % 'Ensemble_Classification(#3#,#''modeseek''#,#''gauss_dd''#,#maxc#)'
    %'DDTools_GaussDD(#0.1#)'
    %'DDTools_Rankboost(#0.1#,#100#)',...
    %'NoOutlier_Rankboost(#0.1#,#100#,#''gendatblockout''#)',...
    %'DDTools_LOF(#0.1#)',...
    %'DDTools_GaussDD(#0.1#)'
%     'Meta_Bagging(#''gauss_dd(A,0.05)''#,#10#,#''maxc''#)',...
%     'Meta_RSM(#''gauss_dd(A,0.05)''#,#10#,#''prodc''#)',...
%     'Meta_Bagging(#''gauss_dd(A,0.05)''#,#10#,#''maxc''#)',...
%     'Meta_Bagging(#''nndd(A,0.05)''#,#10#,#''maxc''#)',...
% 	'Meta_Bagging(#''svdd(A,0.05)''#,#10#,#''maxc''#)',...
%     'Meta_Bagging(#''lofdd(A,0.05)''#,#10#,#''maxc''#)',...
%     'Meta_RSM(#''gauss_dd(A,0.05)''#,#10#,#''prodc''#)',...
%     'Meta_RSM(#''nndd(A,0.05)''#,#10#,#''prodc''#)',...
%     'Meta_RSM(#''svdd(A,0.05)''#,#10#,#''prodc''#)',...
%     'Meta_RSM(#''lofdd(A,0.05)''#,#10#,#''prodc''#)'
    %'Meta_Boosting(#''nndd(A,0.1)''#,#20#,#''prodc''#,#''gendatblockout''#)',...
    %'Meta_Boosting(#''nndd(A,0.1)''#,#20#,#''wvotec''#,#''gendatblockout''#)',...
    %'Meta_Boosting(#''nndd(A,0.1)''#,#20#,#''maxc''#,#''gendatblockout''#)',...
    %'Meta_Boosting(#''nndd(A,0.1)''#,#20#,#''meanc''#,#''gendatblockout''#)'   
    %'Meta_Bagging(#''nndd(A,0.1)''#,#20#,#''meanc''#)',...
    %'Meta_Bagging(#''nndd(A,0.1)''#,#20#,#''maxc''#)',...
    %'Meta_Bagging(#''nndd(A,0.1)''#,#20#,#''minc''#)'   
    %'Meta_Bagging(#''gauss_dd(A,0.1)''#,#15#,#''maxc''#)',...
    %'Meta_Bagging(#''gauss_dd(A,0.1)''#,#15#,#''meanc''#)',...  
};
algo_list_display = {...
    'OC-SVM',...
    'SVDD',...
    %'Parzen',...
    %'LOF',...
    %'LOCI'
};
%algo_list ={'Meta_Bagging(#''parzen_dd(A,0.1)''#,#15#,#''prodc''#)',...
%    'DDTools_GaussDD(#0.1#)','DDTools_ParzenDD(#0.1#)','DDTools_MOG(#0.1#)'};
%algo_list ={'DDTools_GaussDD(#0.1#)','DDTools_ParzenDD(#0.1#)','DDTools_MOG(#0.1#)'};
  %  DDTools_lpDD','DDTools_MOG','PRTools_LMNC','PRTools_RBNC'}
   % ,'PRTools_NEURC','PRTools_RNNC','PRTools_SVC','PRTools_NUSVC','PRTools_KERNELC','PRTools_PERLC', 'PRTools_QUADRC','PRTools_POLYC','PRTools_SUBSC','PRTools_LDC','PRTools_QDC','PRTools_UDC','PRTools_MOGC','PRTools_KNNC','PRTools_PARZENC','PRTools_TREEC','PRTools_NAIVEBC','PRTools_KLLDC','PRTools_PCLDC','PRTools_LOGLC','PRTools_FISJERC','PRTools_NMC','PRTools_NMSC','DDTools_Gauss','DDTools_SVDD','DDTools_Autoenc_dd','DDTools_Kmeans_dd','DDTools_Kcenter_dd','DDTools_Pca_dd','DDTools_Som_dd','DDTools_Mst_dd','DDTools_nndd','DDTools_knndd','DDTools_dnndd','DDTools_MPM','DDTools_incSVDD','DDTools_ParzenDD','MLAlgo_LOF','MLAlgo_SVM'};
%'DDTools_Rob_gauss_dd'
FRACREJ = 0.05;

% Datasets to be evaluated
if 1 == test_type
    dataset_path = '../datasets/test_temp/';
elseif 2 == test_type
    dataset_list = [1 2 3];  % 二维人工数据集选择
end


% Criteria to be evaluated
%crit_list = {'DDTools_F1','DDTools_AUC','OC_MCC'};
%crit_list = {'DDTools_AUC','PRTools_ERROR'};
crit_list = {'DDTools_AUC'};

%% ----------Automatic Checking Part (DO NOT edit) --------------
% Import algorithm invoking templates
temp = importdata('..\config\MLAT_AlgoList.txt');
AlgoList = cell(ceil(length(temp)/3), 2);
for i = 1 : 3 : length(temp)
    AlgoList{round(i/3 + 1), 1} = temp{i};
    AlgoList{round(i/3 + 1), 2} = temp{i+1};
end
MLAT_Conf.AlgoListAll = AlgoList;

temp = importdata('..\config\MLAT_CritList.txt');
CritList = cell(ceil(length(temp)/3), 2);
for i = 1 : 3 : length(temp)
    CritList{round(i/3 + 1), 1} = temp{i};
    CritList{round(i/3 + 1), 2} = temp{i+1};
end
MLAT_Conf.CritListAll = CritList;

% 获取所有测试数据集路径
if 1 == test_type
    fileFolder=fullfile(dataset_path);
    dirOutput=dir(fullfile(fileFolder,'*'));
    dataset_list ={dirOutput.name};
end
